### ISSUE TITLE
Webpage Files

### ISSUE THREAD

**Issue by MattTheNub** [elementnet/e#13]
Create files to be used on #2 (`h_index.html`), like a homepage, explore page, forum homepage, etc. These will be similar to the [homepage](https://scratch.mit.edu), [explore page](https://scratch.mit.edu/explore) and [forum homepage](https://scratch.mit.edu/discuss) on Scratch.
- [ ] Homepage (Featured, etc.)
- [ ] Explore Page
- [ ] Forum Homepage

**Comment by radioblahaj** [comment]
What?

**Comment by MattTheNub** [comment]
@redmangospros Similar to the pages on Scratch?

Like `/h_index.html` would look similar to `https://scratch.mit.edu/`, `/explore/h_index.html` would be like `https://scratch.mit.edu/explore`, and `/discuss/h_index.html` would be like `https://scratch.mit.edu/discuss`.

**Comment by redmangospros** [comment]
how do you want them?

**Comment by MegaCode18** [comment]
@redmangospros They need to be `h_index.html` (short for heroku index, since some of the index files on heroku are different. (i.e. `/sign-in/` would need to exist on heroku but not GitHub pages)

**Comment by redmangospros** [comment]
WOuld i be able to get acces to heroku?

**Comment by MegaCode18** [comment]
@redmangospros What do you mean by "get access"

**Comment by redmangospros** [comment]
I can see the panel.

**Comment by MegaCode18** [comment]
@redmangospros What's your heroku username?

**Comment by redmangospros** [comment]
R V

**Comment by redmangospros** [comment]
[Email Me/heroku email](mailto:aravnarula18@gmail.com)

**Comment by MattTheNub** [comment]
Moved to projects
