### ISSUE TITLE
404 Pages font not working

### ISSUE THREAD

**Issue by MattTheNub** [elementnet/e#14]
### User Info
My user agent is `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36 OPR/49.0.2725.64`
###### Also tested:
* `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0`
* `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586`

### Description of the issue
On the 404 page (and other error pages), the font for `ElementNetwork` isn't working

### Steps to reproduce
1. [Initialize a beta testing server](https://elementnet.github.io/help/beta-testing)
2. Navigate to `localhost:5000/404.html` (or any other error web page)
3. Notice the font on `ElementNetwork`

### Extra info
Here is a screenshot:

![Screenshot](http://u.cubeupload.com/_CodeLyoko/Bug1.png)

**Comment by radioblahaj** [comment]
what do you mean?

**Comment by radioblahaj** [comment]
![noy](https://user-images.githubusercontent.com/21000033/34422221-2c4405be-ebe2-11e7-8351-0d2ae2006ec7.png)

No 404 text in localhost

**Comment by redmangospros** [comment]
hi

**Comment by radioblahaj** [comment]
That is the font,https://fonts.google.com/specimen/Source+Code+Pro

**Comment by MegaCode18** [comment]
@redmangospros Navigate to `localhost:7878/404.html`, not the editor

**Comment by MattTheNub** [comment]
@redmangospros You're looking at the editor, not the 404. Try visiting a page that gives a 404, such as this one: <https://elementnet-dev.herokuapp.com/this/page/does/not/exist/>

**Comment by radioblahaj** [comment]
Let me recheck.

**Comment by SheepTester** [comment]
You [applied](https://github.com/elementnet/e/blob/develop/error.css#L16) the font `Poiret One` to the home button while only [importing `Source Code Pro`](https://github.com/elementnet/e/blob/develop/error.css#L1) from Google fonts

**Comment by MattTheNub** [comment]
oh.
