### ISSUE TITLE
Should beta-testing be moved to help?

### ISSUE THREAD

**Issue by MattTheNub** [elementnet/e#15]
The `beta-testing` page is a quite useful page, especially with contributors not very experienced with NPM. However, when something is changed in `index.js`, the only way to change it is to push to `master` with admin privileges. Should this be done in `elementnet/help` instead?

**Comment by radioblahaj** [comment]
Yes, it should.

**Comment by redmangospros** [comment]
https://t7.rbxcdn.com/551cc9b4881d4baa95ab42ff98c15543

**Comment by MattTheNub** [comment]
Not merged yet

**Comment by radioblahaj** [comment]
Okay, should i do this?

**Comment by MattTheNub** [comment]
@redmangospros #16 needs review
