### ISSUE TITLE
Question: How should we save project data?

### ISSUE THREAD

**Issue by MattTheNub** [elementnet/e#25]
We will need to somehow save the data of the structure of our projects (how the blocks are set up). Should we do so in XML, JSON, or YAML? (see this [Gist](https://gist.github.com/MegaCode18/05f7cea5d74f28fbf5093ccb8790062e))

**Comment by radioblahaj** [comment]
I think Json

**Comment by MattTheNub** [comment]
I, personally, find XML to be more human-readable

**Comment by radioblahaj** [comment]
You're right. But Maybe Json Will be better?

**Comment by MattTheNub** [comment]
For what reason though? XML would be easy to parse, just doing this (via jQuery):
```js
var xml = $.parseXML(xmlData);
var projectName = $(xml).find('name').text();
var projectDesc = $(xml).find('description').text();
scripts[0].blocks[0].spec = $(xml).find('script[number=0] block[number=0]').attr('spec');
// Etc.
```

**Comment by redmangospros** [comment]
`var xml = $.parseXML(xmlData);
var projectName = $(xml).find('name').text();
var projectDesc = $(xml).find('description').text();
scripts[0].blocks[0].spec = $(xml).find('script[number=0] block[number=0]').attr('spec');
// Etc.`
I will tell you soon

**Comment by radioblahaj** [comment]
https://www.quora.com/unanswered/What-Would-be-Better-to-Use-to-save-project-data-XML-YAML-or-JSON

**Comment by SheepTester** [comment]
JSON is also easy to parse (no libraries needed):
```js
var json = JSON.parse(jsonData);
var projectName = json.name;
var projectDesc = json.description;
scripts[0].blocks[0].spec = json.scripts[0].blocks[0].spec;
// etc
```
It's also easy to convert a JS object back into JSON (with `JSON.stringify`)

**Comment by radioblahaj** [comment]
That Is what i was saying! Sheep, do you want to join?

**Comment by radioblahaj** [comment]
https://www.quora.com/What-are-the-advantages-of-XML-over-JSON

**Comment by MattTheNub** [comment]
@SheepTester But, as I said above, the XML method is more human readable (and so is YAML), so it would be better for developers (and things like debugging)

**Comment by radioblahaj** [comment]
True again.

**Comment by MattTheNub** [comment]
We'll probably use JSON for now; worst case scenario we'll just change our method later.
