### ISSUE TITLE
Fix Error Sheets

### ISSUE THREAD

**Issue by radioblahaj** [elementnet/e#26]
We Need to design error pages better!

**Comment by MattTheNub** [comment]
Here are some ideas:
![401](http://u.cubeupload.com/_CodeLyoko/Drawing1.png)
![404](http://u.cubeupload.com/_CodeLyoko/Drawing.png)

**Comment by radioblahaj** [comment]
Nice! Share them with me the rest on google drive!

**Comment by MattTheNub** [comment]
https://goo.gl/7HSCaK

**Comment by radioblahaj** [comment]
We'll Use Them!

**Comment by MattTheNub** [comment]
I'll get started on `26-error-stylesheet` with implementing them in HTML then...

**Comment by radioblahaj** [comment]
And, Should I Share Them?

**Comment by MattTheNub** [comment]
What do you mean?

**Comment by radioblahaj** [comment]
on scratch?

**Comment by MattTheNub** [comment]
You can...

**Comment by radioblahaj** [comment]
Thanks

**Comment by radioblahaj** [comment]
https://www.behance.net/gallery/60350767/Error-Pages-Ui?

**Comment by MattTheNub** [comment]
Fixed by #28 (and #29)

**Comment by radioblahaj** [comment]
500 Error Sheet Coming Like This
![p](https://user-images.githubusercontent.com/21000033/34464251-e578d82e-ee45-11e7-8eef-78a4cf8df5d1.png)

**Comment by MattTheNub** [comment]
Oh, that's because <https://elementnet.js.org> is hosted from `master`, not `develop`. As stated in `CONTRIBUTING.md` (the branching guide), we will not push to `master` unless it's a hotfix for a bug, or a release

Try <https://elementnet-dev.herokuapp.com/500.html>.

**Comment by MattTheNub** [comment]
Also, you're placing a `/` at the end of the URL, essentially trying to access `/500.html/index.html` instead of `/500.html`

**Comment by MattTheNub** [comment]
![It works](http://u.cubeupload.com/_CodeLyoko/itworkze.png)
