### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by MattTheNub** [elementnet/e#4]
Accounts on Heroku page.
- [ ] Sign up via Scratch
- [ ] Convert to EN acct and set password
- [ ] All actions made via Scratch (not asking for email so we can post this on Scratch)

**Comment by radioblahaj** [comment]
WHat About cloud data transfer fom a acc in scratch to make a ac here

**Comment by MattTheNub** [comment]
@redmangospros Don't understand what you mean?

**Comment by MattTheNub** [comment]
Moved to projects
