### ISSUE TITLE
Error pages are pretty ugly

### ISSUE THREAD

**Issue by MattTheNub** [elementnet/e#7]
### User Info
My user agent is `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36 OPR/49.0.2725.64`

### Description of the issue
The error pages are ugly, boring, and don't fit the theme at all (generally pretty lazy)

### Steps to reproduce
1. Trigger a 400, 401, 402, 403, 404, or 500
2. Look at your screen

### Extra info
I'm too lazy to do this myself

**Comment by radioblahaj** [comment]
Argge
